name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the project
        run: mvn clean package

<<<<<<< HEAD
=======
      - name: Install Brotli
        run: sudo apt-get install brotli

      - name: Compress HTML files with Brotli
        run: find target/classes/templates/ -name "*.html" -exec brotli --best {} \;

>>>>>>> dev
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dayz-site:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/dayz-site:latest