name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: ["Run SonarQube and Checkstyle Analysis"]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to DigitalOcean and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/my-project/DayZ-Wiki
            docker compose down
            git pull origin main
            mvn clean package
            docker compose up -d
          EOF